version: '3.4'
services:
  ######################################################################################################################
  # REVERSE PROXY - TRAEFIK
  ######################################################################################################################
  reverse-proxy:
    image: ${REVERSE_PROXY_IMAGE}
    command: '--docker --docker.domain=${CHAMELEON_HOST}'
    container_name: reverse-proxy
    ports:
      - '${CHAMELEON_HTTP_PORT}:80'
      - '${CHAMELEON_HTTPS_PORT}:443'
      - '${CHAMELEON_WS_PORT}:9000'
      - '${CHAMELEON_WSS_PORT}:9001'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik.toml:/traefik.toml'
      - './certs:/etc/traefik/certs'
    restart: always
    networks:
      - net
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: '${FLUENTD_IPV4}:24224'
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: chameleon.{{.Name}}

  ######################################################################################################################
  # LOGGING - FLUENTD
  ######################################################################################################################
  fluentd:
    image: ${FLUENTD_IMAGE}
    container_name: fluentd
    volumes:
      - './logs:/fluentd/log'
    restart: always
    environment:
      - LOGGING_MAIL_SERVER
      - LOGGING_MAIL_USER
      - LOGGING_MAIL_PASSWORD
      - LOGGING_MAIL_RECIPIENT
      - CHAMELEON_HOST
    networks:
      net:
        ipv4_address: ${FLUENTD_IPV4}

  ######################################################################################################################
  # WEB SERVER - NODE
  ######################################################################################################################
  web-server:
    image: ${WEB_SERVER_IMAGE}
    container_name: web-server
    volumes:
      - './www:/opt/app/www'
    labels:
      - traefik.enable=true
      - traefik.backend=web-server
      - 'traefik.frontend.rule=Host:${CHAMELEON_HOST}'
      - traefik.port=3000
      - traefik.docker.network=chameleon_net
    networks:
      - net
    environment:
      - AUTH_TOKEN_SECRET
      - AUTH_COOKIE_NAME
      - AUTH_COOKIE_HTTPS_ONLY
      - AUTH_AD_HOST
      - AUTH_AD_SSL
      - AUTH_AD_BASE_DN
      - NODE_ENV
      - LOGGER_LEVEL
      - FLUENTD_IPV4
      - AUTH_DEBUG_PASSWORD
    restart: always
    depends_on:
      - fluentd

  ######################################################################################################################
  # REST API - NODE
  ######################################################################################################################
  rest-api:
    image: ${REST_API_IMAGE}
    container_name: rest-api
    labels:
      - traefik.enable=true
      - traefik.backend=rest-api
      - 'traefik.frontend.rule=Host:${CHAMELEON_HOST};PathPrefix:/api'
      - traefik.port=3000
      - traefik.docker.network=chameleon_net
    networks:
      net:
        ipv4_address: ${REST_API_IPV4}
    environment:
      - MONGO_DB_HOST
      - MONGO_DB_PORT
      - MONGO_DB_DATABASE
      - MONGO_DB_USER
      - MONGO_DB_PASSWORD
      - K2_DB_HOST
      - K2_DB_INSTANCE
      - K2_DB_DATABASE
      - K2_DB_USER
      - K2_DB_PASSWORD
      - AUTH_TOKEN_SECRET
      - AUTH_COOKIE_NAME
      - AUTH_AD_HOST
      - AUTH_AD_SSL
      - AUTH_AD_BASE_DN
      - AD_USER
      - AD_PASSWORD
      - NODE_ENV
      - CROSSBAR_IPV4
      - CROSSBAR_SECRET_CHAMELEON
      - LOGGER_LEVEL
      - FLUENTD_IPV4
    restart: always
    depends_on:
      - fluentd

  ######################################################################################################################
  # SCHEDULER - NODE
  ######################################################################################################################
  scheduler:
    image: ${SCHEDULER_IMAGE}
    container_name: scheduler
    networks:
      - net
    environment:
      - SCHEDULER_TIMING_MAINTENANCE
      - SCHEDULER_TIMING_K2
      - SCHEDULER_TIMING_PUSHER
      - MONGO_DB_HOST
      - MONGO_DB_PORT
      - MONGO_DB_DATABASE
      - MONGO_DB_USER
      - MONGO_DB_PASSWORD
      - K2_DB_HOST
      - K2_DB_INSTANCE
      - K2_DB_DATABASE
      - K2_DB_USER
      - K2_DB_PASSWORD
      - NODE_ENV
      - CROSSBAR_IPV4
      - CROSSBAR_SECRET_CHAMELEON
      - LOGGER_LEVEL
      - FLUENTD_IPV4
    restart: always
    depends_on:
      - fluentd
      - crossbar

  ######################################################################################################################
  # CROSSBAR
  ######################################################################################################################
  crossbar:
    image: ${CROSSBAR_IMAGE}
    container_name: crossbar
    labels:
      - traefik.enable=true
      - traefik.backend=wamp-api
      - traefik.frontend.entryPoints=ws,wss
      - 'traefik.frontend.rule=Host:${CHAMELEON_HOST};PathPrefix:/ws'
      - traefik.port=3000
      - traefik.docker.network=chameleon_net
    networks:
      net:
        ipv4_address: ${CROSSBAR_IPV4}
    restart: always
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: '${FLUENTD_IPV4}:24224'
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: chameleon.{{.Name}}

  ######################################################################################################################
  # WAMP API (CROSSBAR, NODE)
  ######################################################################################################################
  wamp-api:
    image: ${WAMP_API_IMAGE}
    container_name: wamp-api
    networks:
      - net
    environment:
      - MONGO_DB_HOST
      - MONGO_DB_PORT
      - MONGO_DB_DATABASE
      - MONGO_DB_USER
      - MONGO_DB_PASSWORD
      - K2_DB_HOST
      - K2_DB_INSTANCE
      - K2_DB_DATABASE
      - K2_DB_USER
      - K2_DB_PASSWORD
      - NODE_ENV
      - LOGGER_LEVEL
      - FLUENTD_IPV4
      - CROSSBAR_IPV4
      - CROSSBAR_SECRET_CHAMELEON
      - WAMP_BOOKING_HEARTBEAT_INTERVAL_MS
    restart: always
    depends_on:
      - fluentd
      - crossbar

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: ${CHAMELEON_SUBNET}
