debug = false
logLevel = "WARN" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
checkNewVersion = false

defaultEntryPoints = ["http", "ws"]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
  address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.ws]
    address = ":9000"
