debug = false
logLevel = "WARN" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
checkNewVersion = false

defaultEntryPoints = ["http", "https", "ws", "wss"]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.ws]
    address = ":9000"
  [entryPoints.https]
      address = ":443"
  [entryPoints.ws]
    address = ":9443"
