debug = false
logLevel = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC

defaultEntryPoints = ["http"]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
  address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"
