debug = false
logLevel = "WARN" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
checkNewVersion = false

defaultEntryPoints = ["http", "https", "ws", "wss"]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.ws]
      address = ":9000"
      [entryPoints.ws.redirect]
        entryPoint = "wss"
  [entryPoints.https]
    address = ":443"
     [entryPoints.https.tls]
     [[entryPoints.https.tls.certificates]]
       CertFile = "/etc/traefik/certs/upp.cz.crt"
       KeyFile = "/etc/traefik/certs/upp.cz.key"
  [entryPoints.wss]
    address = ":9443"
     [entryPoints.wss.tls]
     [[entryPoints.wss.tls.certificates]]
       CertFile = "/etc/traefik/certs/upp.cz.crt"
       KeyFile = "/etc/traefik/certs/upp.cz.key"
